language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# 빌드 전에 gradlew의 권한을 추가한다.
before_install:
  - chmod +x gradlew

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  # AWS CodeDeploy는 jar 파일 인식 불가능 - Zip 파일로 압축
  # 현재 위치 (프로젝트) 모든 파일을 압축
  - zip -r commit *
  # TravisCI가 실행중인 위치에서 dir 생성
  - mkdir -p deploy
  - mv commit.zip deploy/commit.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: commit-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    # 위에서 만든 deploy 디렉토리의 파일들만 S3로 전송
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ahyeon31@sookmyung.ac.kr
