language: java
jdk:
  - openjdk1.8

branches:
  only:
    - main

# 빌드 전에 gradlew의 권한을 추가한다.
before_script :
  - chmod +x gradlew

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ahyeon31@sookmyung.ac.kr